import org.wpilib.toolchain.*
import org.gradle.nativeplatform.test.tasks.RunTestExecutable

plugins {
  id 'cpp'
  id 'java'
  id 'google-test'
  id 'idea'
  id 'org.wpilib.WPILibRepositoriesPlugin' version '2027.0.0'
  id 'org.wpilib.NativeUtils' version '2027.13.1'
  id 'org.wpilib.GradleJni' version '2027.0.0'
  id 'org.wpilib.GradleVsCode' version '2027.0.0'
  id 'org.wpilib.GradleRIO' version '2027.0.0-alpha-6'
}

// WPILib Version
ext.wpilibVersion = "2027.+"
ext.releasePath = "$buildDir/maven"
ext.pubVersion = System.getenv("releaseVersion") ?: System.getenv("releaseName") ?: "test"


repositories {
  mavenCentral()
}

wpilibRepositories.use2027Repos()
if (project.hasProperty('releaseMode')) {
  wpilibRepositories.addAllReleaseRepositories(project)
} else {
  wpilibRepositories.addAllDevelopmentRepositories(project)
}


sourceSets {
    main {
        java {
            srcDir "$rootDir/../yams/java/"
        }
    }
}

var javaVersion = "25"

// Apply C++ configuration
apply from: 'config.gradle'

// Apply Java configuration
dependencies {
    implementation wpi.java.deps.wpilib()
    implementation wpi.java.vendor.java()

    implementation "org.wpilib.cscore:cscore-java:$wpilibVersion"
    implementation "org.wpilib.cameraserver:cameraserver-java:$wpilibVersion"
    implementation "org.wpilib.ntcore:ntcore-java:$wpilibVersion"
    implementation "org.wpilib.wpilibj:wpilibj-java:$wpilibVersion"
    implementation "org.wpilib.wpiutil:wpiutil-java:$wpilibVersion"
    implementation "org.wpilib.wpimath:wpimath-java:$wpilibVersion"
    implementation "org.wpilib.wpiunits:wpiunits-java:$wpilibVersion"
    implementation "org.wpilib.datalog:datalog-java:$wpilibVersion"
    implementation "org.wpilib.hal:hal-java:$wpilibVersion"
    implementation "org.ejml:ejml-simple:0.44.0"
    implementation "com.fasterxml.jackson.core:jackson-annotations:2.19.2"
    implementation "com.fasterxml.jackson.core:jackson-core:2.19.2"
    implementation "com.fasterxml.jackson.core:jackson-databind:2.19.2"
    implementation 'org.wpilib.thirdparty.opencv:opencv-java:2027-4.13.0-3'

    nativeDebug wpi.java.deps.wpilibJniDebug(wpi.platforms.desktop)
    nativeDebug wpi.java.vendor.jniDebug(wpi.platforms.desktop)
    simulationDebug wpi.sim.enableDebug()

    nativeRelease wpi.java.deps.wpilibJniRelease(wpi.platforms.desktop)
    nativeRelease wpi.java.vendor.jniRelease(wpi.platforms.desktop)
    simulationRelease wpi.sim.enableRelease()

    testImplementation platform("org.junit:junit-bom:5.11.4")
    testImplementation "org.junit.jupiter:junit-jupiter-api"
    testImplementation "org.junit.jupiter:junit-jupiter-params"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
    testImplementation "org.mockito:mockito-core:5.3.1"
    testImplementation "org.mockito:mockito-junit-jupiter:5.3.1"
}

// Set up java tests
test {
    useJUnitPlatform()
    systemProperty 'junit.jupiter.extensions.autodetection.enabled', 'true'
    testLogging {
        events "failed"
        exceptionFormat = "full"
    }
}

wpi.sim.addGui().defaultEnabled = true
wpi.sim.addDriverstation()
wpi.java.configureTestTasks(test)

tasks.test {
    // Disable test when running 'build' task, but enable when running 'test' task directly
    enabled = !gradle.startParameter.taskNames.contains('build')
}

task googleTest {
    description = 'Runs the Google Test C++ unit tests for the current platform'
    group = 'Verification'
}

tasks.whenTaskAdded { task ->
    if (task instanceof RunTestExecutable) {
        task.enabled = !gradle.startParameter.taskNames.contains('build')
        if (task.name.contains(NativePlatforms.desktop.capitalize()) && task.name.contains('Debug')) {
            googleTest.dependsOn task
        }
    }
}

if (project.hasProperty('onlylinuxarm32') || project.hasProperty('onlylinuxarm64') || project.hasProperty('onlywindowsarm64') || project.hasProperty('onlylinuxsystemcore')) {
    test.enabled = false
}

tasks.withType(JavaCompile) {
    options.compilerArgs.add '-XDstringConcat=inline'
    options.encoding = 'UTF-8'
}

javadoc {
    title = "Yet Another Mechanism System API"
    destinationDir = file("$releasePath/javadocs")
    options {
        encoding = 'UTF-8'
        charSet = 'UTF-8'
        links "https://docs.oracle.com/en/java/javase/$javaVersion/docs/api/",
                'https://github.wpilib.org/allwpilib/docs/release/java/',
                'https://codedocs.revrobotics.com/java/',
                'https://api.ctr-electronics.com/phoenix6/stable/java/',
                'https://api.ctr-electronics.com/phoenix/stable/java/'
        tags 'todo:X"',
            'apiNote:a:API Note:',
            'implSpec:a:Implementation Requirements:',
            'implNote:a:Implementation Note:'
        overview "$rootDir/../yams/java/overview.html"
    }
}
ext.getCurrentArch = {
    return NativePlatforms.desktop
}

def systemArch = getCurrentArch()

model {
  components {
      YAMS(NativeLibrarySpec) {
          sources {
              cpp {
                  source {
                      srcDirs "$rootDir/../yams/cpp/src"
                      include '**/*.cpp'
                  }
                  exportedHeaders {
                      srcDirs "$rootDir/../yams/cpp/include"
                  }
              }
          }
          nativeUtils.useRequiredLibrary(it, 'wpilib_shared')
          wpi.vendor.nativeVendor.cpp(it)
      }
  }
  testSuites {
      YAMSTest {
          binaries.all {
              buildable = !gradle.startParameter.taskNames.contains('build')
          }
          sources.cpp {
              source {
                  srcDir 'src/test/native/cpp'
                  include '**/*.cpp'
              }
              exportedHeaders {
                  srcDirs 'src/test/native/include'
              }
          }

          /*binaries.all {
//              lib library: 'VendorDriver', linkage: 'shared'

              def arch = it.targetPlatform.name
              if (systemArch == arch && it.buildType.name == 'debug') {
                  def filePath = it.tasks.install.installDirectory.get().toString() + File.separatorChar + 'lib'
                  test.dependsOn it.tasks.install
                  test.systemProperty 'java.library.path', filePath
                  test.environment 'LD_LIBRARY_PATH', filePath
                  test.workingDir filePath
              }
          }*/

          nativeUtils.useRequiredLibrary(it, "wpilib_shared", "googletest_static")
          wpi.vendor.nativeVendor.cpp(it)
      }

  }
}

build.dependsOn javadoc
apply from: 'publish.gradle'

wrapper {
  gradleVersion = '9.4.1'
}
