// Copyright (c) 2026 Yet Another Software Suite
// SPDX-License-Identifier: LGPL-3.0-or-later
// Ported from the WCP 2026 Competitive Concept (MIT, see LICENSE-WCP).

package first.robot;

import com.ctre.phoenix6.CANBus;
import org.wpilib.hardware.bus.CANPort;

public final class Ports {
    // CAN Buses. Systemcore has no "rio" bus; its first onboard CAN port takes that role.
    public static final CANBus kRoboRioCANBus = new CANBus(CANPort.CAN_S0);
    public static final CANBus kCANivoreCANBus = new CANBus("main");

    // Talon FX IDs
    public static final int kIntakePivot = 10;
    public static final int kIntakeRollers = 11;
    public static final int kFloor = 12;
    public static final int kFeeder = 13;
    public static final int kShooterLeft = 14;
    public static final int kShooterMiddle = 15;
    public static final int kShooterRight = 16;
    public static final int kHanger = 18;

    // PWM Ports
    public static final int kHoodLeftServo = 3;
    public static final int kHoodRightServo = 4;

    // Swerve (CANivore). Previously generated by Phoenix Tuner X in TunerConstants.
    public static final int kPigeon = 45;

    public static final int kFrontLeftDrive = 3;
    public static final int kFrontLeftSteer = 2;
    public static final int kFrontLeftEncoder = 21;

    public static final int kFrontRightDrive = 1;
    public static final int kFrontRightSteer = 0;
    public static final int kFrontRightEncoder = 20;

    public static final int kBackLeftDrive = 5;
    public static final int kBackLeftSteer = 4;
    public static final int kBackLeftEncoder = 22;

    public static final int kBackRightDrive = 7;
    public static final int kBackRightSteer = 6;
    public static final int kBackRightEncoder = 23;
}
