name: YAMS CI
on:
  push:
    branches: [ "master" ]
    paths:
      - "examples/**"
      - "yams/**"
      - "vendordep/**"
  pull_request:
    paths:
      - "examples/**"
      - "yams/**"
      - "vendordep/**"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: gradle/actions/wrapper-validation@v6

  build-cross:
    name: Build - ${{ matrix.artifact-name }}
    needs: [validation]
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: wpilib/systemcore-cross-debian:trixie
            artifact-name: SystemCore
            build-options: "-Ponlylinuxsystemcore"
          - container: wpilib/aarch64-cross-debian:trixie
            artifact-name: Arm64
            build-options: "-Ponlylinuxarm64"
          - container: wpilib/systemcore-cross-debian:trixie
            artifact-name: Linux
            build-options: ""
    runs-on: ubuntu-24.04
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v7
      - name: Configure git safe directory
        run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      - name: Install toolchain
        run: ./gradlew installSystemCoreToolchain
        working-directory: vendordep
      - name: Publish
        run: ./gradlew publish ${{ matrix.build-options }}
        working-directory: vendordep
      - uses: actions/upload-artifact@v7
        with:
          name: maven-${{ matrix.artifact-name }}
          path: vendordep/build/maven/

  build-linux:
    name: Build - Linux
    needs: [validation]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: vendordep
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
      - run: chmod +x gradlew
      - name: Install doxygen and graphviz
        run: sudo apt-get install -y doxygen graphviz
      - uses: gradle/actions/setup-gradle@v6
      - name: Install toolchain
        run: ./gradlew installSystemCoreToolchain
      - name: Publish
        run: ./gradlew publish
      - uses: actions/upload-artifact@v7
        with:
          name: maven-linux
          path: vendordep/build/maven/

  test-cpp:
    name: C++ unit tests
    needs: [build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: vendordep
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
      - run: chmod +x gradlew
      - uses: gradle/actions/setup-gradle@v6
      - name: Install toolchain
        run: ./gradlew installSystemCoreToolchain
      - uses: actions/download-artifact@v7
        with:
          name: maven-linux
          path: vendordep/build/maven/
      - name: C++ unit tests
        run: ./gradlew googleTest
        continue-on-error: true

  test-java:
    name: Java unit tests
    needs: [build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: vendordep
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
      - run: chmod +x gradlew
      - uses: gradle/actions/setup-gradle@v6
      - name: Install toolchain
        run: ./gradlew installSystemCoreToolchain
      - uses: actions/download-artifact@v7
        with:
          name: maven-linux
          path: vendordep/build/maven/
      - name: Java unit tests
        run: ./gradlew test

  build-host:
    name: Build - ${{ matrix.artifact-name }}
    needs: [validation]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025
            artifact-name: windows
            gradlew: ./gradlew.bat
            architecture: x64
          - os: macos-15
            artifact-name: macos
            gradlew: ./gradlew
            architecture: aarch64
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: vendordep
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          architecture: ${{ matrix.architecture }}
      - name: Make gradlew executable
        if: runner.os != 'Windows'
        run: chmod +x gradlew
      - uses: gradle/actions/setup-gradle@v6
      - name: Install toolchain
        run: ${{matrix.gradlew}} installSystemCoreToolchain
      - name: Build java and C++
        run: ${{matrix.gradlew}} build
      - name: Publish
        run: ${{ matrix.gradlew }} publish
      - uses: actions/upload-artifact@v7
        with:
          name: maven-${{ matrix.artifact-name }}
          path: vendordep/build/maven/

  combine:
    name: Combine
    needs: [build-cross, build-linux, build-host]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: maven-*
          path: combined-maven/
          merge-multiple: true
      - uses: actions/upload-artifact@v7
        with:
          name: maven-combined
          path: combined-maven/
